---
name: CI

on:
  pull_request:
  push:
    branches:
      - main

# MacOS runner information: https://github.com/actions/runner-images/tree/main/images/macos

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, macos-15, macos-14]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v

      - name: Check `browserctl` runs
        run: ./.build/debug/browserctl list

  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Lint
        run: swiftlint lint --reporter github-actions-logging
