---
name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  VERSION: ${{ github.ref_name }}

permissions:
  contents: write # To create releases

jobs:
  create:
    runs-on: ubuntu-slim
    steps:
      - name: Create GitHub Release
        run: gh release create "$VERSION" --draft --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [create]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build executable
        run: |
          swift build -c release
          echo "BIN=.build/release/browserctl" >> "$GITHUB_ENV"

      - name: Generate manpage
        run: |
          swift package plugin generate-manual
          echo "MAN=.build/plugins/GenerateManual/outputs/browserctl/browserctl.1" >> "$GITHUB_ENV"

      - name: Archive name
        run: echo "ARCHIVE=browserctl-$VERSION" >> "$GITHUB_ENV"

      - name: Create archive directories
        run: |
          mkdir -p "$ARCHIVE"/{bin,share/{man/man1,completions}}
          cp "$BIN" "$ARCHIVE"/bin
          cp "$MAN" "$ARCHIVE"/share/man/man1
          cp {README.md,LICENSE} "$ARCHIVE"

      - name: Generate Completions
        run: |
          "$BIN" --generate-completion-script bash > "$ARCHIVE"/share/completions/browserctl.bash
          "$BIN" --generate-completion-script zsh > "$ARCHIVE"/share/completions/_browserctl
          "$BIN" --generate-completion-script fish > "$ARCHIVE"/share/completions/browserctl.fish

      - name: Create archive
        run: |
          tar -czvf "$ARCHIVE.tar.gz" "$ARCHIVE"
          echo "ASSET=$ARCHIVE.tar.gz" >> "$GITHUB_ENV"

      - name: Upload release archive
        run: gh release upload "$VERSION" "$ASSET"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [build]
    runs-on: ubuntu-slim
    steps:
      - name: Publish release
        run: gh release edit "$VERSION" --draft=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump-homebrew:
    needs: [build]
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: peter-bread/bump-homebrew@v2
        with:
          cellarman-app-client-id: ${{ vars.CELLARMAN_APP_CLIENT_ID }}
          cellarman-app-private-key: ${{ secrets.CELLARMAN_APP_PRIVATE_KEY }}
          tap-owner: peter-bread
