---
name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  TAG: ${{ github.ref_name }}

permissions:
  contents: write # To create releases

jobs:
  create:
    runs-on: ubuntu-slim
    steps:
      - name: Determine version number
        id: version
        uses: peter-bread/extract-version@v1
        with:
          ref: ${{ env.TAG }}
          should-fail: true

      - name: Create GitHub Release
        run: gh release create "$TAG" --draft --generate-notes --title "Browserctl $VERSION"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
    outputs:
      version: ${{ steps.version.outputs.version }}

  build:
    needs: [create]
    runs-on: macos-latest
    env:
      VERSION: ${{ needs.create.outputs.version }}
    steps:
      - uses: actions/checkout@v7

      - name: Build executable
        run: |
          swift build -c release
          echo "BIN=.build/release/browserctl" >> "$GITHUB_ENV"

      - name: Check that version was embedded correctly
        run: |
          VERSION_OUTPUT=$("$BIN" --version)
          [[ $VERSION_OUTPUT == "browserctl $VERSION" ]]

      - name: Generate manpage
        run: |
          swift package plugin generate-manual
          echo "MAN=.build/plugins/GenerateManual/outputs/browserctl/browserctl.1" >> "$GITHUB_ENV"

      - name: Determine archive name
        run: echo "ARCHIVE=browserctl-$VERSION" >> "$GITHUB_ENV"

      - name: Create archive directories
        run: |
          mkdir -p "$ARCHIVE"/{bin,share/{man/man1,completions}}
          cp "$BIN" "$ARCHIVE"/bin
          cp "$MAN" "$ARCHIVE"/share/man/man1
          cp {README.md,LICENSE} "$ARCHIVE"

      - name: Generate Completions
        run: |
          "$BIN" --generate-completion-script bash > "$COMP_DIR"/browserctl.bash
          "$BIN" --generate-completion-script zsh > "$COMP_DIR"/_browserctl
          "$BIN" --generate-completion-script fish > "$COMP_DIR"/browserctl.fish
        env:
          COMP_DIR: ${{ env.ARCHIVE }}/share/completions

      - name: Create archive
        run: |
          tar -czvf "$ARCHIVE.tar.gz" "$ARCHIVE"
          echo "ASSET=$ARCHIVE.tar.gz" >> "$GITHUB_ENV"

      - name: Upload release archive
        run: gh release upload "$TAG" "$ASSET"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [build]
    runs-on: ubuntu-slim
    steps:
      - name: Publish release
        run: gh release edit "$TAG" --draft=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump-homebrew:
    needs: [build]
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: peter-bread/bump-homebrew@v2
        with:
          cellarman-app-client-id: ${{ vars.CELLARMAN_APP_CLIENT_ID }}
          cellarman-app-private-key: ${{ secrets.CELLARMAN_APP_PRIVATE_KEY }}
          tap-owner: peter-bread
